### ISSUE TITLE
SimpleFieldSelect not working in IE11

### ISSUE THREAD

**Issue by ernstblaauw** [mediassarQlikBranch/SimpleFieldSelect#24] opened 2019-12-19 11:42 UTC
Hi,

You have made a great plugin, thanks!
However, we cannot get it to work in IE11 (both version 1.9.23 and 1.9.26) - users only see the title / header, but no selection options. This is happening with both Sense September 2019 and November 2019.
Looking at your changelog, I think IE11 should work. What kind of log files do you need to investigate this issue?

Thanks!

**Comment by ernstblaauw** [comment] 2019-12-20 10:05
Update: it is the Qlik Checkbox

**Comment by mediassarQlikBranch** [comment] 2020-01-09 20:52
Hi
I tried with my IE11 and it Qlik Checkbox works. Can you send screenshot? Can u check console logs? if there is any? 

![kuva](https://user-images.githubusercontent.com/30590553/72103781-989c8f80-3332-11ea-85de-34a4f1de6ab1.png)

**Comment by EugeneZide** [comment] 2020-01-20 10:17
![image](https://user-images.githubusercontent.com/58972038/72718514-283e0b80-3b87-11ea-8126-2da656ca8956.png)


Here is screenshot, IE 11 left, Chrome right (sorry, i'm in Russia , so all words in russian)

**Comment by mediassarQlikBranch** [comment] 2020-03-01 18:35
I would need the console output., There must be some error. PRess F12 and reload page.

**Comment by EugeneZide** [comment] 2020-03-02 07:13
SCRIPT1002: Синтаксическая ошибка SimpleFieldSelect.js (1824,34)
// syntax error (my translation)
SCRIPT5007: Не удалось получить свойство "__esModule" ссылки, значение которой не определено или является NULL
// can't get property  "__esModule" , value of which is undefined or null (my translation)
setup-view.18e9edd82a29b0b79ca3.js (8,1001248)
SCRIPT5007: Не удалось получить свойство "__esModule" ссылки, значение которой не определено или является NULL
// same error
setup-view.18e9edd82a29b0b79ca3.js (8,1001248)

**Comment by Massimo1990** [comment] 2020-03-28 15:41
Hi all, thank you again Mediassar for this beautiful extension. I have experienced the same error of Eugene. Do you have any tips or work around to let the extension working in IE11? thank you

**Comment by mediassarQlikBranch** [comment] 2020-03-28 15:48
Hi

can you help me and check console logs. I’m not able to reproduce the error.. Most likely this is easy to fix but we need to knwo the error!

br Matti

Lähettäjä: Massimo <notifications@github.com>
Lähetetty: lauantai 28. maaliskuuta 2020 17.42
Vastaanottaja: mediassarQlikBranch/SimpleFieldSelect <SimpleFieldSelect@noreply.github.com>
Kopio: Matti Punkeri <Matti.Punkeri@mediassar.fi>; Comment <comment@noreply.github.com>
Aihe: Re: [mediassarQlikBranch/SimpleFieldSelect] SimpleFieldSelect not working in IE11 (#24)


Hi all, thank you again Mediassar for this beautiful extension. I have experienced the same error of Eugene. Do you have any tips or work around to let the extension working in IE11? thank you

**Comment by Massimo1990** [comment] 2020-03-29 09:24
Hi @mediassarQlikBranch , good news it seems that the error has gone after that I have installed the latest version (beginning of march) - my fault not have checked to have installed the latest version!

However this was the error I had in the previous version:
![image](https://user-images.githubusercontent.com/19785946/77845444-4dff1680-71af-11ea-97c7-13cdce342bbd.png)
If you can check and then confirm that effectively it was resolved in the last version would be great to have it mentioned in the Change Log!

thank you again for your brilliant work!
BR
Massimo

**Comment by mediassarQlikBranch** [comment] 2020-03-29 09:51
Well, there was a IE 11 issue back in October 2019 releases. It was fixed but I didn’t understand that this was the issue with your case most likely too. Implementation back then used certain Javascript coding style that wasn’t supported by IE but was then changed...
So most likely your issue is the same as in changelog 1.9.25 - IE 11 support for search
Anyway, great that you got it working and thanks for the feedback!

br Matti

Lähettäjä: Massimo <notifications@github.com>
Lähetetty: sunnuntai 29. maaliskuuta 2020 12.25
Vastaanottaja: mediassarQlikBranch/SimpleFieldSelect <SimpleFieldSelect@noreply.github.com>
Kopio: Matti Punkeri <Matti.Punkeri@mediassar.fi>; Mention <mention@noreply.github.com>
Aihe: Re: [mediassarQlikBranch/SimpleFieldSelect] SimpleFieldSelect not working in IE11 (#24)


Hi @mediassarQlikBranch<https://github.com/mediassarQlikBranch> , good news it seems that the error has gone after that I have installed the latest version (beginning of march) - my fault not have checked to have installed the latest version!

However this was the error I had in the previous version:
[image]<https://user-images.githubusercontent.com/19785946/77845444-4dff1680-71af-11ea-97c7-13cdce342bbd.png>
If you can check and then confirm that effectively it was resolved in the last version would be great to have it mentioned in the Change Log!

thank you again for your brilliant work!
BR
Massimo

**Comment by mediassarQlikBranch** [comment] 2020-03-29 10:08
Fixed in version 1.9.25

**Closed by mediassarQlikBranch** 2020-03-29 10:08 UTC
